### ISSUE TITLE
gar_repo_name variable needs to be variablized in the build files

### ISSUE THREAD

**Issue by sanketnadkarni** [cldcvr/gcifi-lz#7]
- the gar_repo_name variable input is accepted in terraform.tfvars in the bootstrap stage
- build files have the artifact registry hardcoded as `gcf-lz` and it needs to be variablized using the wrapper script

**Comment by amansingh14** [comment]
Its been fixed with new release v2[](https://github.com/cldcvr/gcifi-lz/releases/tag/v2.0.0)
